// Generated by CoffeeScript 1.6.3
(function() {
  module.exports = function(options) {
    var model;
    return model = function(req, res, next) {
      var getSession, getUser, _ref;
      if (!((req.getModel != null) && typeof req.getModel === typeof Function)) {
        throw new Error('use racer.modelMiddleware() before model()');
      }
      if (((_ref = req.session) != null ? _ref.id : void 0) == null) {
        throw new Error('use publishId() before model()');
      }
      getSession = function() {
        return req.getModel().at('irons_sessions.' + req.session.id);
      };
      getUser = function(id) {
        return req.getModel().at('irons_users.' + id);
      };
      req.irons = {
        getSession: getSession,
        getUser: getUser
      };
      return next();
    };
  };

}).call(this);
