// Generated by CoffeeScript 1.6.3
(function() {
  var passport;

  passport = require('passport');

  module.exports = function(options) {
    var passportSerializers;
    return passportSerializers = function(req, res, next) {
      var _ref;
      if (((_ref = req.irons) != null ? _ref.fetchUser : void 0) == null) {
        throw new Error('use ironsModel() before passportSerializers()');
      }
      passport.serializeUser(function(user, done) {
        return done(null, user.get('id'));
      });
      passport.deserializeUser(function(id, done) {
        if (!id) {
          return done(new Error('User ID missing'));
        }
        return req.irons.fetchUser(id, function(err, user) {
          return done(err, user);
        });
      });
      return next();
    };
  };

}).call(this);
