// Generated by CoffeeScript 1.6.3
(function() {
  var passport;

  passport = require('passport');

  module.exports = function(options) {
    var passportSerializers;
    return passportSerializers = function(req, res, next) {
      var _ref;
      if (!((((_ref = req.irons) != null ? _ref.getUser : void 0) != null) && typeof req.irons.getUser === typeof Function)) {
        throw new Error('use model() before passportSerializers()');
      }
      passport.serializeUser(function(user, done) {
        console.log(user);
        return done(null, user.id || user.get('id'));
      });
      passport.deserializeUser(function(id, done) {
        var user;
        if (!id) {
          return done(new Error('User ID missing'));
        }
        user = req.irons.getUser(id);
        return user.fetch(function(err) {
          if (err) {
            return done(err);
          }
          return done(null, user);
        });
      });
      return next();
    };
  };

}).call(this);
