// Generated by CoffeeScript 1.6.3
(function() {
  module.exports = function(options) {
    var publishId;
    return publishId = function(req, res, next) {
      var model, _base;
      if (!((req.getModel != null) && typeof req.getModel === typeof Function)) {
        throw new Error('use store.modelMiddleware() before publishIds()');
      }
      model = req.getModel();
      (_base = req.session).id || (_base.id = model.id());
      model.set('_irons.sessionId', req.session.id);
      return next();
    };
  };

}).call(this);
