// Generated by CoffeeScript 1.6.3
(function() {
  module.exports = function(options) {
    var publishIds;
    return publishIds = function(req, res, next) {
      var model, _ref;
      if (!((req.getModel != null) && typeof req.getModel === typeof Function)) {
        throw new Error('use store.modelMiddleware() before publishIds()');
      }
      if (((_ref = req.session) != null ? _ref.id : void 0) == null) {
        throw new Error('use sessionId() before publishIds()');
      }
      model = req.getModel();
      model.set('_irons.sessionId', req.session.id);
      if (req.user != null) {
        model.set('_irons.userId', req.user.get('id'));
      }
      return next();
    };
  };

}).call(this);
