// Generated by CoffeeScript 1.6.3
(function() {
  var express, expressApp;

  express = require('express');

  expressApp = express();

  module.exports = function(options, model) {
    var config, passport;
    config = require('./defaults');
    if (options) {
      config.load(options);
      config.validate();
    }
    passport = require('./passport')(config);
    return expressApp.use(express.bodyParser()).use(express.methodOverride()).use(express.cookieParser()).use(express.cookieSession({
      key: 'irons.id',
      secret: config.get('session.secret')
    })).use(require('./middleware/sessionId')()).use(require('./middleware/ironsModel')()).use(require('./middleware/passportSerializers')()).use(passport.initialize()).use(passport.session()).use(require('./middleware/publishIds')()).post('/register', require('./controllers/register')(config)).post('/login', require('./controllers/login')(config)).post('/logout', require('./controllers/logout')(config));
  };

}).call(this);
