// Generated by CoffeeScript 1.6.3
(function() {
  var express, expressApp, passport;

  passport = require('passport');

  express = require('express');

  expressApp = express();

  module.exports = function(options, model) {
    var config;
    config = require('./defaults');
    if (options) {
      config.load(options);
      config.validate();
    }
    return expressApp.use(express.bodyParser()).use(express.methodOverride()).use(express.cookieParser()).use(express.cookieSession({
      key: 'irons.id',
      secret: config.get('session.secret')
    })).use(require('./middleware/publishId')()).use(require('./middleware/model')()).use(require('./middleware/passportSerializers')()).use(passport.initialize()).use(passport.session()).post('/register', require('./controllers/acceptRegistration')(options));
  };

}).call(this);
