// Generated by CoffeeScript 1.6.3
(function() {
  var passport;

  passport = require('passport');

  module.exports = function(options) {
    var login;
    return login = function(req, res, next) {
      options.load({
        passport: {
          failureRedirect: req.get('Referer')
        }
      });
      return passport.authenticate('local', options.get('passport'), function(err, user, info) {
        if (err) {
          return next(err);
        }
        if (!user) {
          return res.send(401, 'Authentication failure, please try again.');
        }
        return req.login(user, function(err) {
          if (err) {
            return next(err);
          }
          return res.send(200, 'Logged in.');
        });
      })(req, res, next);
    };
  };

}).call(this);
