// Generated by CoffeeScript 1.6.3
(function() {
  var passport;

  passport = require('passport');

  module.exports = function(options) {
    var login;
    return login = function(req, res, next) {
      options.load({
        passport: {
          failureRedirect: req.get('Referer')
        }
      });
      return passport.authenticate('local', options.get('passport'), function(err, user, info) {
        console.log("err: " + err + ", user: " + user + ", info: " + info);
        if (err) {
          return next(err);
        }
        if (user) {
          return req.login(user, function(err) {
            if (err) {
              return next(err);
            }
            return res.send(200, JSON.stringify({
              userId: user.get('id'),
              toast: {
                type: 'success',
                msg: 'Logged in.'
              }
            }));
          });
        } else {
          return res.send(401, JSON.stringify({
            userId: null,
            toast: {
              type: 'error',
              msg: info
            }
          }));
        }
      })(req, res, next);
    };
  };

}).call(this);
