// Generated by CoffeeScript 1.6.3
(function() {
  module.exports = function(options) {
    var logout;
    return logout = function(req, res, next) {
      req.logout();
      return res.send(200, JSON.stringify({
        userId: false,
        toast: {
          type: 'success',
          msg: 'Logged out.'
        }
      }));
    };
  };

}).call(this);
